packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@eslint/js": ^9.39.2
  "@types/node": ^22.19.9
  eslint: ^9.39.2
  prettier: ^3.8.1
  typescript: ^5.9.3

catalogs:
  react19:
    "@types/react": 19.2.13
    "@types/react-dom": 19.2.3
    react: 19.2.4
    react-dom: 19.2.4

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
