// Query TypeMap
import "@sanity/client";

/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Theme = {
  _id: string;
  _type: "theme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Region = {
  _id: string;
  _type: "region";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type RegionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "region";
};

export type ThemeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "theme";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishedDate: string;
  excerpt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  authors?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  regions?: Array<
    {
      _key: string;
    } & RegionReference
  >;
  themes?: Array<
    {
      _key: string;
    } & ThemeReference
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Publication = {
  _id: string;
  _type: "publication";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishedDate: string;
  excerpt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  authors?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  regions?: Array<
    {
      _key: string;
    } & RegionReference
  >;
  themes?: Array<
    {
      _key: string;
    } & ThemeReference
  >;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishedDate: string;
  excerpt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  authors?: Array<
    {
      _key: string;
    } & PersonReference
  >;
  regions?: Array<
    {
      _key: string;
    } & RegionReference
  >;
  themes?: Array<
    {
      _key: string;
    } & ThemeReference
  >;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  role?: string;
  bio?: string;
  socialMediaLinks?: Array<
    {
      _key: string;
    } & SocialMediaLink
  >;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  eventDate?: string;
  excerpt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SocialMediaLink = {
  _type: "socialMediaLink";
  platform: "linkedin" | "x" | "facebook" | "instagram" | "youtube" | "github";
  url: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Theme
  | Slug
  | Region
  | SanityImageAssetReference
  | PersonReference
  | RegionReference
  | ThemeReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Publication
  | Post
  | Person
  | Page
  | Event
  | SocialMediaLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/queries/author.ts
// Variable: AUTHOR_BY_SLUG_QUERY
// Query: *[_type == "author" && slug.current == $slug][0]{    name  }
export type AUTHOR_BY_SLUG_QUERY_RESULT = null;

// Source: src/queries/author.ts
// Variable: ALL_AUTHOR_SLUGS_QUERY
// Query: *[_type == "author" && defined(slug.current)].slug.current
export type ALL_AUTHOR_SLUGS_QUERY_RESULT = Array<never>;

// Source: src/queries/category.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0]{    title  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = null;

// Source: src/queries/category.ts
// Variable: ALL_CATEGORY_SLUGS_QUERY
// Query: *[_type == "category" && defined(slug.current)].slug.current
export type ALL_CATEGORY_SLUGS_QUERY_RESULT = Array<never>;

// Source: src/queries/page.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    title  }
export type PAGE_BY_SLUG_QUERY_RESULT = {
  title: string;
} | null;

// Source: src/queries/page.ts
// Variable: ALL_PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)].slug.current
export type ALL_PAGE_SLUGS_QUERY_RESULT = Array<string>;

// Source: src/queries/person.ts
// Variable: PEOPLE_QUERY
// Query: *[_type == "person" && defined(slug.current)] {    _id,    name,    "slug": slug.current,    image {        "id": asset._ref,  "preview": asset->metadata.lqip,  hotspot { x, y },  crop {    bottom,    left,    right,    top,  }    },    role  }
export type PEOPLE_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  image: {
    id: string | null;
    preview: string | null;
    hotspot: {
      x: number;
      y: number;
    } | null;
    crop: {
      bottom: number;
      left: number;
      right: number;
      top: number;
    } | null;
  } | null;
  role: string | null;
}>;

// Source: src/queries/person.ts
// Variable: PERSON_BY_SLUG_QUERY
// Query: *[_type == "person" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    image {        "id": asset._ref,  "preview": asset->metadata.lqip,  hotspot { x, y },  crop {    bottom,    left,    right,    top,  }    },    role,    bio,    socialMediaLinks  }
export type PERSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  image: {
    id: string | null;
    preview: string | null;
    hotspot: {
      x: number;
      y: number;
    } | null;
    crop: {
      bottom: number;
      left: number;
      right: number;
      top: number;
    } | null;
  } | null;
  role: string | null;
  bio: string | null;
  socialMediaLinks: Array<
    {
      _key: string;
    } & SocialMediaLink
  > | null;
} | null;

// Source: src/queries/person.ts
// Variable: ALL_PERSON_SLUGS_QUERY
// Query: *[_type == "person" && defined(slug.current)].slug.current
export type ALL_PERSON_SLUGS_QUERY_RESULT = Array<string>;

// Source: src/queries/post.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    title  }
export type POST_BY_SLUG_QUERY_RESULT = {
  title: string;
} | null;

// Source: src/queries/post.ts
// Variable: ALL_POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)].slug.current
export type ALL_POST_SLUGS_QUERY_RESULT = Array<string>;

// Source: src/queries/publication.ts
// Variable: PUBLICATION_BY_SLUG_QUERY
// Query: *[_type == "publication" && slug.current == $slug][0]{    title  }
export type PUBLICATION_BY_SLUG_QUERY_RESULT = {
  title: string;
} | null;

// Source: src/queries/publication.ts
// Variable: ALL_PUBLICATION_SLUGS_QUERY
// Query: *[_type == "publication" && defined(slug.current)].slug.current
export type ALL_PUBLICATION_SLUGS_QUERY_RESULT = Array<string>;

declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "author" && slug.current == $slug][0]{\n    name\n  }\n': AUTHOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "author" && defined(slug.current)].slug.current\n': ALL_AUTHOR_SLUGS_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0]{\n    title\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "category" && defined(slug.current)].slug.current\n': ALL_CATEGORY_SLUGS_QUERY_RESULT;
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    title\n  }\n': PAGE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "page" && defined(slug.current)].slug.current\n': ALL_PAGE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "person" && defined(slug.current)] {\n    _id,\n    name,\n    "slug": slug.current,\n    image {\n      \n  "id": asset._ref,\n  "preview": asset->metadata.lqip,\n  hotspot { x, y },\n  crop {\n    bottom,\n    left,\n    right,\n    top,\n  }\n\n    },\n    role\n  }\n': PEOPLE_QUERY_RESULT;
    '\n  *[_type == "person" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    image {\n      \n  "id": asset._ref,\n  "preview": asset->metadata.lqip,\n  hotspot { x, y },\n  crop {\n    bottom,\n    left,\n    right,\n    top,\n  }\n\n    },\n    role,\n    bio,\n    socialMediaLinks\n  }\n': PERSON_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "person" && defined(slug.current)].slug.current\n': ALL_PERSON_SLUGS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    title\n  }\n': POST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)].slug.current\n': ALL_POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "publication" && slug.current == $slug][0]{\n    title\n  }\n': PUBLICATION_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "publication" && defined(slug.current)].slug.current\n': ALL_PUBLICATION_SLUGS_QUERY_RESULT;
  }
}
